name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # - uses: leafo/gh-actions-lua@v8.0.0
      #   with:
      #     luaVersion: "5.1.5"
      
      # - uses: leafo/gh-actions-luarocks@v4.0.0

      # - name: install ldoc
      #   run: |
      #     luarocks install ldoc
      
      # - name: Set version
      #   id: set_version
      #   run: |
      #     version=`echo $GITHUB_REF | cut -d '/' -f 3`
          
      - name: Muddle
        uses: demonnic/build-with-muddler@v1.2
      
      - name: Upload MPackage
        uses: actions/upload-artifact@v2
        with:
          name: MDK-package
          path: build/tmp/
      
      - name: Run Busted tests
        uses: demonnic/test-in-mudlet@main
        with:
          pretestPackage: ${{ github.workspace }}/build/MDK.mpackage

